// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

func InitApp() *App {
	process := NewProcess()
	plot := NewPlot()
	app := NewApp(process, plot)
	return app
}
